robot:
  type: mg3000
  port: /dev/ttyACM1
  joints:
    wrist_roll:
      max_torque: 1000 # in promille of max torque
      p: 10
      i: 0
      d: 10
      max_velocity: 50 # in ticks/s
      max_acceleration: 20 # in ticks/s^2
      reduction_ratio: 0.33333333 # 1/3
    gripper_left:
      max_torque: 1000
      p: 20
      i: 0
      d: 20
      max_velocity: 50
      max_acceleration: 20
      reduction_ratio: 1.0