robot:
  type: mg3000
  port: /dev/ttyACM0
  calibration_dir: "/home/magnus/waveshare_driver/ExternalImplementations/lerobot/src/lerobot/robots/mg3000/calibration"
  id: "mg3000_1"
  joints:
    wrist_roll:
      Torque_Limit: 150 # in promille of max torque
      P_Coefficient: 10
      I_Coefficient: 0
      D_Coefficient: 10
      Goal_Velocity: 0 # in ticks/s
      Acceleration: 15 # in ticks/s^2
    gripper_left:
      Max_Torque_Limit: 50
      P_Coefficient: 20
      I_Coefficient: 0
      D_Coefficient: 20
      Goal_Velocity: 0
      Acceleration: 0